### ISSUE TITLE
selectors

### ISSUE THREAD

**Issue by trinpham** [trinpham/wi21-cse110-lab3#3]
### issue
include selectors

### todo
- [x] class selector (.class)
- [x] id selector (#id)
- [x] universal selector (*)
- [x] element selector (element)
- [x] attribute selector (e.g. [attribute=foo])
- [x] pseudo-class selectors (e.g. p::hover)
- [x] grouping / combinators
   - [x] selector list (element, element)
   - [x] descendant combinator (element element)
   - [x] child combinator (element > element)
   - [x] general sibling combinator (element ~ element)
   - [x] adjacent sibling combinator (element + element)
   - [x] combining two selectors (element.class)
