### ISSUE TITLE
css topics pt2

### ISSUE THREAD

**Issue by trinpham** [trinpham/wi21-cse110-lab3#5]
### issue
include css topics pt2

### todo
- [x] unit
   - [x] 3 relative
   - [x] 3 absolute
- [x] box model 
![boxmodel](https://user-images.githubusercontent.com/56616602/105554994-533ccd00-5cbd-11eb-8368-c52938b9dc55.gif)
   - [x] margins
      - [x] long (margin-top, margin-bottom, margin-left, margin-right)
      - [x] short (margin: top right bottom left)
      - [x] auto
   - [x] padding
      - [x] long (padding-top, padding-bottom, padding-left, padding-right)
      - [x] shorthand (padding: top right bottom left)
   - [x] height/width
      - [x] set the height and width for an element
- [x] text
   - [x] color
   - [x] text-decoration
   - [x] text-align
