### ISSUE TITLE
css topics pt3

### ISSUE THREAD

**Issue by trinpham** [trinpham/wi21-cse110-lab3#6]
### issue
include css topics pt3

### todo
- [x] fonts
   - [x] include and use a 3rd party font (https://fonts.google.com/). you can load the font in either your HTML or your CSS
- [x] display
   - [x] experiment with these types: none, block, inline-block, inline. include at least two of them in your page.
- [x] max-width/min-width
   - [x] width has to be variable (like a percentage)
- [x] position
   - [x] experiment with these attributes: static, relative, fixed, absolute, sticky. Include at least two of them in your page.
- [x] pseudo-class
   - [x] :hover
   - [x] :active
