### ISSUE TITLE
css topics pt4

### ISSUE THREAD

**Issue by trinpham** [trinpham/wi21-cse110-lab3#7]
### issue
include css topics pt4

### todo
- [x] [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
   - [x] must have more than two children within the element that is using flexbox. must use minimum three of the flexbox related attributes.
- [x] [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)
   - [x] must have more than two children within the element that is using grid. must use minimum three of the flexbox related attributes.
- [x] media query
   - [x] at least one query based on the screen width
