### ISSUE TITLE
add media to folder

### ISSUE THREAD

**Issue by trinpham** [trinpham/wi21-cse110-lab3#8]
### issue
add media to folder

### todo
- [x] make new folder
- [x] add media to folder
- [x] update in html file
